// Types
export type {
    UserIdentity,
    MemberSearchStrategy,
    User,
    Thread,
    ThreadMember,
    ThreadMemberInfo,
    ThreadMemberRole,
    ThreadMessage,
    MessageRole,
    ContentPart,
    TextContentPart,
    ThinkingContentPart,
    ToolCallContentPart,
    ToolResultContentPart,
    AttachmentContentPart,
    OpaqueContentPart,
    ProviderReplayData,
    SearchResult,
    MemoryEntry,
    StatusCode,
    ErrorCode,
} from "./types/index.js";

export { STATUS_CODES, ERROR_CODES } from "./types/index.js";

// Attachments
export type { AttachmentKind, AttachmentInfo, AttachmentLimits } from "./attachments/index.js";
export {
    ATTACHMENT_LIMITS,
    normalizeMimeType,
    classifyAttachmentMimeType,
    isModelReadableMimeType,
    isValidUtf8,
} from "./attachments/index.js";

// Interfaces
export { formatLoggedError, NOOP_PROVIDER_LOGGER, zodTool } from "./interfaces/index.js";
export type {
    IAgentProvider,
    AgentCapabilities,
    AgentConfig,
    ProviderLogger,
    AgentMessage,
    AgentMessageRole,
    AgentRunOptions,
    AgentStreamChunk,
    TextDeltaChunk,
    ThinkingPartChunk,
    OpaquePartChunk,
    ReplayDataChunk,
    StatusChunk,
    CitationsChunk,
    ToolCallChunk,
    ToolResultChunk,
    UsageChunk,
    AgentUsage,
    Citation,
    ShouldRespondResult,
    IPersistenceProvider,
    CreateThreadOptions,
    ListThreadsOptions,
    ThreadListCursor,
    AppendMessageOptions,
    LoadMessagesOptions,
    SaveAttachmentOptions,
    AttachmentRecord,
    AttachmentData,
    ISearchProvider,
    SearchDocument,
    IndexDocumentOptions,
    IndexBatchResult,
    SemanticSearchFilter,
    SemanticSearchOptions,
    SearchResultGroup,
    IEmbeddingsProvider,
    ITool,
    JsonSchema,
    ZodToolDefinition,
    IMemoryProvider,
    SaveMemoryOptions,
    SearchMemoryOptions,
    ListMemoryOptions,
} from "./interfaces/index.js";

// Events
export type {
    SendMessageEvent,
    JoinThreadEvent,
    LeaveThreadEvent,
    TypingStartEvent,
    TypingStopEvent,
    InviteMemberEvent,
    RemoveMemberEvent,
    UpdateMemberRoleEvent,
    ClientToServerEvent,
    PartDeltaEvent,
    MessageStatusEvent,
    MessageCompleteEvent,
    NewMessageEvent,
    TypingEvent,
    PresenceUpdateEvent,
    MemberJoinedEvent,
    MemberLeftEvent,
    MemberRoleChangedEvent,
    ThreadUpdatedEvent,
    ThreadCreatedEvent,
    ErrorEvent,
    ServerFeatures,
    WelcomeEvent,
    ServerToClientEvent,
} from "./events/index.js";

// DTOs (schemas are values, not just types)
export {
    textContentPartSchema,
    thinkingContentPartSchema,
    toolCallContentPartSchema,
    toolResultContentPartSchema,
    opaqueContentPartSchema,
    attachmentContentPartSchema,
    contentPartSchema,
    createThreadRequestSchema,
    updateThreadRequestSchema,
    updateThreadUserStateRequestSchema,
    chatRequestSchema,
    transcriptionResponseSchema,
    attachmentInfoSchema,
    inviteMemberRequestSchema,
    removeMemberRequestSchema,
    updateMemberRoleRequestSchema,
    searchRequestSchema,
    memorySearchRequestSchema,
    paginationQuerySchema,
    threadListQuerySchema,
    userSearchQuerySchema,
    userSearchResultWireSchema,
    userSearchResultListWireSchema,
    updateUserRequestSchema,
    threadSearchQuerySchema,
} from "./dto/index.js";

export type {
    CreateThreadRequest,
    UpdateThreadRequest,
    UpdateThreadUserStateRequest,
    ChatRequest,
    TranscriptionResponse,
    AttachmentInfoWire,
    InviteMemberRequest,
    RemoveMemberRequest,
    UpdateMemberRoleRequest,
    SearchRequest,
    MemorySearchRequest,
    PaginationQuery,
    ThreadListQuery,
    UserSearchQuery,
    UserSearchResultWire,
    UpdateUserRequest,
    ThreadSearchQuery,
} from "./dto/index.js";

// Endpoints
export {
    API_PREFIX,
    WS_PATH,
    THREADS_PATH,
    THREAD_SEARCH_PATH,
    USERS_SEARCH_PATH,
    USERS_ME_PATH,
    TRANSCRIBE_PATH,
    ATTACHMENTS_PATH,
    threadPath,
    threadMessagesPath,
    threadMembersPath,
    threadUserStatePath,
    attachmentPath,
    threadWireSchema,
    threadListWireSchema,
    threadMessageWireSchema,
    threadMessageListWireSchema,
    threadMemberInfoWireSchema,
    threadMemberInfoListWireSchema,
    userProfileWireSchema,
    threadSearchHitWireSchema,
    threadSearchResultWireSchema,
    threadSearchResponseWireSchema,
} from "./endpoints/index.js";

export type {
    ThreadWire,
    ThreadMessageWire,
    ThreadMemberInfoWire,
    UserProfileWire,
    ThreadSearchHitWire,
    ThreadSearchResultWire,
    ThreadSearchResponseWire,
} from "./endpoints/index.js";
